MovieShopMVC/Controllers/CastController.cs
using ApplicationCore.Contract.Service;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Controllers
{
    public class CastController: Controller
    {
        private readonly ICastService _castService;

        public CastController(ICastService  castService)
        {
            _castService = castService;
        }

        // showing details of the movie
        public IActionResult CastDetail(int id)
        {
            var cast = _castService.GetCastDetails(id);
            return View(cast);
        }
    }
}

MovieShopMVC/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting.Internal;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ApplicationCore.Contract.Service;


namespace MovieShopMVC.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieService _movieService;

        public MovieController(IMovieService movieService)
        {
            _movieService = movieService;
        }

        // showing details of the movie
        public async Task<IActionResult> Details(int id)
        {
            var movie = await _movieService.GetMovieDetails(id);
            return View(movie);
        }
        public async Task<IActionResult> Genre(int Id, int pageSize = 30, int pageNumber = 1)
        {
            var pagedMovies = await _movieService.GetMoviesByGenre(Id, pageSize, pageNumber);

            return View("PagedMovies", pagedMovies);
        }
        
    }
}

MovieShopMVC/Views/Movie/Details.cshtml
@model ApplicationCore.Model.MovieDetailsModel




<div class="container">
    <div class="row">
        <div class="col-2"style="width:250px">
            <img src="@Model.PosterUrl" class="img-fluid" alt="@Model.Title" />
        </div>
        <div class="col-2">
 
        </div>
        <div class="col-5">
            <h2>
                @Model.Title
            </h2>
            <div class="container">
                <div class="row">
                    <h6 style="float: left; font-size: 15px">@Model.RunTime m | @Model.ReleaseDate</h6>

                    @foreach (var genre in @Model.Genres)
                    {   
                        <h6 style="font-size: 15px; float: left"><span class="badge bg-secondary">@genre.Name</span></h6>
                    }
                </div>
                <div class="row">
                    <h5><span class="badge bg-secondary">8.8</span></h5>
                </div>
                <div class="row">
                    <h3 style="font-size:18px;">
                        @Model.Overview
                    </h3>
                </div>
            </div>
        </div>
        <div class="col-1">
 
        </div>
        <div class="col-2 position-absolute top-10 end-0">

            <br /><br />
            <div>
            <button type="button" class="btn btn-dark btn-block" data-bs-toggle="modal" data-bs-target="#myModal">Review</button>
            <div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="myModalLabel">Review</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                Rating
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <li class="dropdown-item">1</li>
                                    <li class="dropdown-item">2</li>
                                    <li class="dropdown-item">3</li>
                                    <li class="dropdown-item">4</li>
                                    <li class="dropdown-item">5</li>
                                    <li class="dropdown-item">6</li>
                                    <li class="dropdown-item">7</li>
                                    <li class="dropdown-item">8</li>
                                    <li class="dropdown-item">9</li>
                                    <li class="dropdown-item">10</li>
                                </ul>
                            </div>
                            <form>
                                <div class="form-group">
                                    <label for="comment">Write Review:</label>
                                    <textarea class="form-control" rows="5" id="comment"></textarea>
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-dark">Submit</button>
                        </div>
                    </div>
      
                </div>
            </div>
            </div>
            <br /><br />
            <div>
                    <button type="button" class="btn btn-primary btn-block" data-bs-toggle="modal" data-bs-target="#exampleModal">
                      BUY $@Model.Price
                    </button>
                    <div class="modal fade" id="staticBackdrop" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="staticBackdropLabel">Buy Movie</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <p>I confirm to buy this movie with $@Model.Price</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    <button type="button" class="btn btn-dark">Purchase</button>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-3 start-0" > 
             <h5>MOVIE FACTS</h5>
             <div>
                 <h6>Release Date   <span class="badge bg-secondary">@Model.ReleaseDate</span></h6>
                 <hr>
                 <h6>Run Time   <span class="badge bg-secondary">@Model.RunTime m</span></h6>
                 <hr>
                 <h6>Box office   <span class="badge bg-secondary">@Model.Revenue</span></h6>
                 <hr>
                 <h6>Budget   <span class="badge bg-secondary">@Model.Budget</span></h6>
                 <hr>
             </div>
             <h5>TRAILERS</h5>
             @foreach (var trailer in @Model.Trailers)
             {
                <div>
                    <a href="@trailer.TrailerUrl">@trailer.Name</a>
                </div>   
             }
        </div>
        <div class="col-2">
            
        </div>
        <div class="col-4">
            <h5>CAST</h5>
            @foreach (var cast in @Model.Casts)
            {
                <div class="container">
                    <div class="row">
                        <div class="col-2">
                            <img src="@cast.ProfilePath" class="img-fluid" alt="@cast.Name">
                        </div>
                        <div class="col-1">
                        </div>
                        <div class="col-4">
                            <a asp-controller="Cast" asp-action="CastDetail" asp-route-id="@cast.Id">
                                @cast.Name
                            </a>
                        </div>
                        <div class="col-1">

                        </div>
                        <div class="col-4">
                            @cast.Character
                        </div>
                    </div>
                </div>
            <hr />
            }
        </div>
        <div class="col-3">
            
        </div>
    </div>
</div>


 

MovieShopMVC/Views/Movie/PagedMovies.cshtml
@model ApplicationCore.Model.PagedResultSetModel<ApplicationCore.Model.MovieCardModel>

<div class="rounded">
    <div class="container bg-light">
        <div class="row">
            @foreach (var movie in Model.PagedData)
            {
                <div class="col-6 col-lg-3 col-sm-4 col-xl-2">

                    <partial name="_MovieCard" model="movie" />
                </div>

            }
        </div>
    </div>
</div>

@{
    var previousDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a class="btn btn-primary @previousDisabled" asp-action="Genre" asp-controller="Movie" asp-route-pageNumber="@(Model.PageNumber-1)">
    Previous
</a>

<a class="btn btn-primary @nextDisabled" asp-action="Genre" asp-controller="Movie" asp-route-pageNumber="@(Model.PageNumber + 1)">
    Next
</a>